更新：先整一个i18n看看
UnrealMultiple/TShockPlugin pull request #448
Opened 2024-09-01 04:36 UTC by THEXN

2024-09-01 04:38 UTC, ACaiCat approved these changes

2024-09-01 04:40 UTC, sgkoishi requested changes

2024-09-01 04:40 UTC, sgkoishi commented on src/AdditionalPylons/i18n/en-US.po
> +msgstr "The number of Jungle crystal towers has reached its maximum."
Pylon?

2024-09-01 04:40 UTC, sgkoishi commented on src/AutoPluginManager/AutoPluginManager.csproj
> +	<ItemGroup>
EmbeddedResource is already defined in template.target

2024-09-01 04:40 UTC, sgkoishi commented on src/AutoPluginManager/Plugin.cs
> +    public override string Name => GetString("AutoPluginManager");
wait for TShock to init

2024-09-02 08:55 UTC, LaoSparrow approved these changes

2024-09-02 12:48 UTC, merged