修复：VeinMiner的多项问题
UnrealMultiple/TShockPlugin pull request #512
Opened 2024-10-04 13:47 UTC by THEXN

### 更新插件/修复BUG
- [x] 插件已修改版本号
- [x] 更新插件README.md中的更新日志
- [x] 插件可以正常工作
### 其他
- [x] ❤️Cai我喜欢你 
- 修复：背包满的时候去挖达到可获得奖励数量的矿，只会挖掉一个矿，但却会给予一个奖励物品，然后就可以用这个刷奖励
- 完善消息提示逻辑
#510

2024-10-04 14:55 UTC, Controllerdestiny requested changes

2024-10-04 14:55 UTC, Controllerdestiny commented on src/VeinMiner/README.md
> +  "当矿石上方有这些物品时，该处矿石不被挖掘": [
逐渐羽化

2024-10-04 14:55 UTC, Controllerdestiny commented on src/VeinMiner/README.md
> +  "当矿石上方有这些物品时，该处矿石不被挖掘": [
换个命名吧

2024-10-04 15:51 UTC, THEXN commented on src/VeinMiner/README.md
> +  "当矿石上方有这些物品时，该处矿石不被挖掘": [
要换的话干脆其他也换了

2024-10-04 16:12 UTC, ACaiCat approved these changes

2024-10-04 16:13 UTC, ACaiCat commented
不过话说, 改了配置插件不会爆掉吗233
虽然大部分人也不会配这个插件

2024-10-04 16:22 UTC, THEXN commented
> 不过话说, 改了配置插件不会爆掉吗233 虽然大部分人也不会配这个插件

不会爆，但是会用不了，要改配置文件，而且不会把以前配置干没

2024-10-05 03:50 UTC, Controllerdestiny approved these changes

2024-10-05 03:50 UTC, merged