添加插件：AutoAirItem 自动垃圾桶插件
UnrealMultiple/TShockPlugin pull request #527
Opened 2024-10-22 15:25 UTC by THEXN

### 添加插件
- [x] 插件已加入解决方案 (Plugin.sln)
- [x] 插件项目已导入template.targets (<Import Project="..\template.targets"/>)
- [x] 插件信息已加入仓库文档 (README.md)
- [x] 插件的文件夹名字和插件的插件项目名字一样 (XXX/XXX.csproj)  
- [x] 添加插件单独的README.md文件 (XXX/README.md)
- [ ] 插件可以正常工作
- [ ] ### 其他
- [x] ❤️羽学我喜欢你 
        
> [!NOTE]
> 没用的选项自行删掉哦~

2024-10-22 17:17 UTC, Controllerdestiny requested changes

2024-10-22 17:17 UTC, Controllerdestiny commented on src/AutoAirItem/AutoAirItem.cs
> +        this._reloadHandler = (_) => LoadConfig();
这。。

2024-10-22 17:17 UTC, Controllerdestiny commented on src/AutoAirItem/AutoAirItem.cs
> +    internal static Configuration Config = new();
要不就换成一个普通方法吧，这样有点太刻意了。

2024-10-22 18:10 UTC, Controllerdestiny commented
顺便支持一下i18n

2024-10-23 13:44 UTC, THEXN commented
> 顺便支持一下i18n

搞定

2024-10-24 09:58 UTC, Controllerdestiny approved these changes

2024-10-24 09:58 UTC, merged