更新彩虹聊天v1.0.7
UnrealMultiple/TShockPlugin pull request #546
Opened 2024-10-29 08:55 UTC by 1242509682

# 详细说明
v1.0.7
修复了指令屏蔽问题
加入了全局控制开关的指令与对应配置项
修复了渐变色聊天时的物品图标显示
加入了当玩家使用指令开启渐变时默认会关闭随机色的逻辑
关于随机色的图标修复工作：
羽学表示放弃，甚至对这个功能是否有存在的必要性，都持有怀疑态度。

# PR 自查表
### 更新插件/修复BUG
- [ x ] 插件已修改版本号
- [ x ] 更新插件README.md中的更新日志
- [ x ] 插件可以正常工作
### 其他
- [ x ] ❤️熙恩我喜欢你

2024-10-30 05:48 UTC, Controllerdestiny requested changes

2024-10-30 05:48 UTC, Controllerdestiny commented on src/AutoAirItem/AutoAirItem.cs
> +    private static void ReloadConfig(ReloadEventArgs args = null!)
ReloadEventArgs? args = null

2024-10-30 05:48 UTC, Controllerdestiny commented on src/AutoAirItem/AutoAirItem.cs
> +        var data = Data.Items.FirstOrDefault(x => x.Name == plr.Name);
用Any判断是否存在

2024-10-30 05:52 UTC, Controllerdestiny requested changes

2024-10-30 05:52 UTC, Controllerdestiny commented on src/AutoAirItem/AutoAirItem.cs
>          foreach (var plr in TShock.Players.Where(plr => plr != null && plr.Active && plr.IsLoggedIn))
感觉不如直接foreach TShock.Players，而且这个处理放在PlayerSlot也行啊

2024-10-31 18:01 UTC, LaoSparrow approved these changes

2024-10-31 19:19 UTC, merged