添加插件：AutoFish 自动钓鱼插件
UnrealMultiple/TShockPlugin pull request #551
Opened 2024-11-05 01:14 UTC by 1242509682

# 详细说明

我实在不会装GetText，翻译英文只能搁浅了，
希望有国外友人能帮帮我。
I really don't know how to install GetText, so my English translation project has been put on hold. I hope some international friends can help me out.

# PR 自查表
### 添加插件
- [ x ] 插件已加入解决方案 (Plugin.sln)
- [ x ] 插件项目已导入template.targets (<Import Project="..\template.targets"/>)
- [ x ] 插件信息已加入仓库文档 (README.md)
- [ x ] 插件的文件夹名字和插件的插件项目名字一样 (XXX/XXX.csproj)  
- [ x ] 添加插件单独的README.md文件 (XXX/README.md)
- [ x ] 插件可以正常工作
### 其他
- [ x ] ❤️少司命我喜欢你

2024-11-05 08:53 UTC, Controllerdestiny requested changes

2024-11-05 08:53 UTC, Controllerdestiny commented on src/AutoFish/AutoFish.cs
> +        GetDataHandlers.NewProjectile += this.ProjectNew!;
这个!干嘛的

2024-11-05 08:53 UTC, Controllerdestiny commented on src/AutoFish/AutoFish.cs
> +                    if (args.Projectile.ai[1] <= 0)
<

2024-11-05 08:54 UTC, Controllerdestiny commented
等待补充i18n

2024-11-05 16:16 UTC, 1242509682 commented on src/AutoFish/AutoFish.cs
> +        GetDataHandlers.NewProjectile += this.ProjectNew!;
不知道 删掉就黄了- -

2024-11-07 09:28 UTC, Controllerdestiny approved these changes

2024-11-07 09:29 UTC, merged