update 禁地表弹幕 v2.0
UnrealMultiple/TShockPlugin pull request #608
Opened 2024-12-13 22:45 UTC by 1242509682

# 详细说明

- 2.0.0
- 重构所有代码,移除指令方法
- 加入了数据库存储逻辑用于查找需要销毁弹幕的对应玩家
- 加入了物品掉落、图格还原等方法逻辑
- 支持全类型种子不同地图大小

# PR 自查表
### 添加插件
- [ ] 插件已加入解决方案 (Plugin.sln)
- [ ] 插件项目已导入template.targets (<Import Project="..\template.targets"/>)
- [ ] 插件信息已加入仓库文档 (README.md)
- [ ] 插件的文件夹名字和插件的插件项目名字一样 (XXX/XXX.csproj)  
- [ ] 添加插件单独的README.md文件 (XXX/README.md)
- [ ] 插件可以正常工作
### 更新插件/修复BUG
- [ ] 插件已修改版本号
- [ ] 更新插件README.md中的更新日志
- [ ] 插件可以正常工作
### 其他
- [ ] ❤️熙恩我喜欢你 
        
> [!NOTE]
> 没用的选项自行删掉哦~

2024-12-15 03:12 UTC, ACaiCat requested changes

2024-12-15 03:12 UTC, ACaiCat commented on src/SurfaceBlock/Configuration.cs
> +    protected override string Filename => "禁地表弹幕";
Filename => "SurfaceBlock"; 貌似会更好

2024-12-15 03:12 UTC, ACaiCat commented on src/SurfaceBlock/Database.cs
神秘，都用Laz了要不考虑一下ORM ❤️

2024-12-15 03:12 UTC, ACaiCat commented on src/SurfaceBlock/SurfaceBlock.cs
> +            DB.ClearData(); //关服自动清理玩家数据
啊？ 这个DB感觉可以直接改成个列表之类的缓存

2024-12-15 03:12 UTC, ACaiCat commented on src/SurfaceBlock/SurfaceBlock.cs
> +                name = "未知";
需要GetString()

2024-12-16 01:34 UTC, 1242509682 commented on src/SurfaceBlock/SurfaceBlock.cs
> +            DB.ClearData(); //关服自动清理玩家数据
确实 用内存来缓存重启服务器自己就会清空数据了 考虑到现在写数据库的插件源码太繁杂了 所以当作一个写法示例用了

2024-12-17 04:02 UTC, Controllerdestiny approved these changes

2024-12-17 12:38 UTC, closed without merging