添加插件：玩家位置随机交换
UnrealMultiple/TShockPlugin pull request #627
Opened 2024-12-28 04:45 UTC by THEXN

# PR 自查表
### 添加插件
- [ ] 插件已加入解决方案 (Plugin.sln)
- [ ] 插件项目已导入template.targets (<Import Project="..\template.targets"/>)
- [ ] 插件信息已添加至对应manifest.json
- [ ] 插件的文件夹名字和插件的插件项目名字一样 (XXX/XXX.csproj)  
- [ ] 添加插件单独的README.md文件 (XXX/README.md)
- [ ] 插件可以正常工作
### 更新插件/修复BUG
- [ ] 插件已修改版本号
- [ ] 更新插件README.md中的更新日志
- [ ] 插件可以正常工作
### 其他
- [ ] ❤️少司命我喜欢你

2024-12-28 10:28 UTC, ACaiCat commented on src/Chameleon/Chameleon.cs
> +                    if (knownIps != null && player.IP == knownIps[^1] || Configuration.Instance.VerifyloginIP)
if (knownIps != null && player.IP == knownIps[^1] || Configuration.Instance.VerifyloginIP)

2024-12-28 10:35 UTC, ACaiCat requested changes

2024-12-28 10:35 UTC, ACaiCat commented on src/Chameleon/Chameleon.cs
> +                    if (knownIps != null && player.IP == knownIps[^1] || Configuration.Instance.VerifyloginIP)
if (Configuration.Instance.VerifyloginIP && knownIps?.LastOrDefault() == player.IP)

2024-12-28 10:35 UTC, ACaiCat commented on src/Chameleon/README.md
> +是否ip验证允许自定义
添加`验证登录IP是否一致`配置

2024-12-28 10:35 UTC, ACaiCat commented on src/PlayerRandomSwapper/PlayerRandomSwapper.cs
> +        var players = TShock.Players.Where(p => p != null && p.Active && !p.Dead).ToList();
不要.ToList()

2024-12-28 10:35 UTC, ACaiCat commented on src/PlayerRandomSwapper/i18n/en_US.po
`en-US.po`

2024-12-28 13:48 UTC, ACaiCat approved these changes

2024-12-28 16:23 UTC, ACaiCat requested changes

2024-12-28 16:23 UTC, ACaiCat commented on src/Chameleon/Chameleon.cs
> +            if (Configuration.Instance.VerifyloginIP && JsonConvert.DeserializeObject <string[]>(account.KnownIps) is var kownIps && (knownIps is null || player.IP != kownIps.LastOrDefault()))
if (Configuration.Instance.VerifyloginIP && JsonConvert.DeserializeObject <string[]>(account.KnownIps) is var kownIps && (knownIps is null || player.IP != kownIps.Last()))

2024-12-28 17:15 UTC, ACaiCat approved these changes

2024-12-29 04:23 UTC, xuyuwtu approved these changes

2024-12-29 04:25 UTC, merged